### ISSUE TITLE
API key for demo

### ISSUE THREAD

**Issue by hjkiri** [symisc/pixlab#2]
The scripts use an API key which isn't made available. Can I at least get it to check how the product works?

**Comment by symisc** [comment]
API keys are available from your PixLab dashboard at https://pixlab.io/dashboard. Once you select an adequate plan, you'll be able to generate your API keys immediately.

**Comment by stojankukrika** [comment]
Can I get demo without leave credit card or paypall account?

**Comment by symisc** [comment]
API keys are available from your PixLab dashboard at https://pixlab.io/dashboard. Once you select an adequate plan, you'll be able to generate your API keys immediately.

**Comment by stojankukrika** [comment]
I do not see it. It's showing me to select country and then want to select payment method :(
