### ISSUE TITLE
An error occur

### ISSUE THREAD

**Issue by FiziYeoh** [symisc/pixlab#8]
I got an error:
Notice: Undefined variable: pix in C:\xampp\htdocs\votesystem\face_compare.php on line 16

Fatal error: Uncaught Error: Call to a member function get() on null in C:\xampp\htdocs\votesystem\face_compare.php:16 Stack trace: #0 {main} thrown in C:\xampp\htdocs\votesystem\face_compare.php on line 16.

Line number 16 and onwards is : 
if( !$pix->get('facecompare',[
	'src'    => $src,
	'target' => $target,
	]) ){
	echo $pix->get_error_message()."\n";
	die;
}
echo "Same Face?: ". ($pix->json->same_face?'True':'False') ."\n";
echo "Confidence: ". $pix->json->confidence."\n";
?>

**Comment by symisc** [comment]
@FiziYeoh, you need to include the file **pixlab.php** in your directory. You can download it from https://github.com/symisc/pixlab-php. An usage example is shown at the README of that repository.

**Comment by FiziYeoh** [comment]
I already added it from the beginning. Its okay i solved it. $pix is not variables so just added $pix = new Pixlab($key); it work just fine. Thanks
