### ISSUE TITLE
Can I compare picture that store locally?

### ISSUE THREAD

**Issue by FiziYeoh** [symisc/pixlab#9]
Hello, Im currently using the facecompare and I notice that the facecompare can only compare between 2 picture that are uploaded on the internet (by using link). May I know whether it can compare 2 picture that are stored locally in my machine or retrieve from database (phpmyadmin)? if yes how to write the path for $src and $target. thank you

**Comment by symisc** [comment]
Hi Fizi,

You have to upload that file into the PixLab server and use the output link as input for /[facecompare](https://pixlab.io/cmd?id=facecompare). To upload a local file into PixLab, call first the /[store](https://pixlab.io/cmd?id=store) endpoint and the output URL that you can pass later to /[faceomapre](https://pixlab.io/cmd?id=facecompare). An usage example of the file upload operation is shown at: https://github.com/symisc/pixlab/blob/master/PHP/upload_media.php.
